stages:
  - name: Test
    steps:
      - runScriptConfig:
          image: golang:1.13.9
          shellScript: |-
            # Disable command tracing when installing credentials
            # for security
            { set +x; } 2>/dev/null

            # Install bot credentials
            mkdir -p -m 0600 ~/.ssh
            echo "${RANCHER_CI_SSH_KEY}" > ~/.ssh/id_ed25519
            chmod 400 ~/.ssh/id_ed25519

            # Prepare CA roots for packaging in later stages
            cat /etc/ssl/certs/* > ca-roots.crt

            # Re-enable command tracing
            set -x

            # Configure git access
            git config --global url."ssh://git@github.com:".insteadOf "https://github.com"
            git config --global url."ssh://git@bitbucket.org:".insteadOf "https://bitbucket.org"
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts

            # Run tests
            go test -race -cover -v -failfast ./...

            # Prepare binary for packaging in later stages
            make linux
        envFrom:
          - sourceName: rancher-ci-credentials
            sourceKey: ssh_key
            targetKey: RANCHER_CI_SSH_KEY
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: general/echo-server:${CICD_GIT_TAG}
          pushRemote: true
          registry: registry.bryk.io
        env:
          PLUGIN_DEBUG: "true"
    when:
      event:
        include:
          - tag
timeout: 30