apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
    version: 0.1.0
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo-server
      version: 0.1.0
  template:
    metadata:
      name: echo-server
      labels:
        app: echo-server
        version: 0.1.0
    spec:
      restartPolicy: Always
      containers:
        - name: echo-server
          image: gcr.io/fairbank-io/echo-server:0.1.0
          imagePullPolicy: Always
          ports:
            - name: rpc
              containerPort: 9090
            - name: http
              containerPort: 9091
          env:
            - name: ECHO_HTTP
              value: "true"
