apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-server-http
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/protocol: http
    ingress.kubernetes.io/content-type-nosniff: "true"
    ingress.kubernetes.io/browser-xss-filter: "true"
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/load-balancer-method: "drr"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    # traefik.frontend.passTLSCert: true
    # traefik.ingress.kubernetes.io/ssl-redirect: true
spec:
  tls:
    - secretName: cert-fairbank-io
  rules:
    - host: echo.fairbank.io
      http:
        paths:
          - path: /echo
            backend:
              serviceName: echo-server
              servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-server-rpc
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/protocol: h2c
    traefik.ingress.kubernetes.io/frontend-entry-points: http
    traefik.ingress.kubernetes.io/load-balancer-method: "drr"
    # traefik.ingress.kubernetes.io/frontend-entry-points: http
spec:
  rules:
    - host: echo.fairbank.io
      http:
        paths:
          - backend:
              serviceName: echo-server
              servicePort: rpc
