apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-service-rpc
  annotations:
    kubernetes.io/ingress.class: "http2"
    nginx.ingress.kubernetes.io/backend-protocol: "grpcs"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
    - host: rpc.pixative.com
      http:
        paths:
          - backend:
              serviceName: echo-service
              servicePort: rpc
