apiVersion: v1
kind: Service
metadata:
  name: echo-server
  annotations:
    traefik.ingress.kubernetes.io/load-balancer-method: "drr"
spec:
  selector:
    app: echo-server
    version: 0.1.0
  ports:
    - name: rpc
      port: 9090
      targetPort: rpc
    - name: http
      port: 9091
      targetPort: http
